---

- name: webservers.yml | All roles
  hosts: webservers
  sudo: True

  roles:
    - { role: common,                   tags: ["common"] }
    - { role: iver.nginx,               tags: ["nginx"] }
