---

postgresql_cluster_reset      : true
postgresql_data_directory     : "/mnt/db/postgresql/{{postgresql_version}}/{{postgresql_cluster_name}}"
postgresql_listen_addresses   : ["0.0.0.0"]
postgresql_pg_hba_trust_hosts : ["0.0.0.0/0"]

postgresql_databases          : [
                                  {name: "database_name"},
                                  {name: "database_name_qa"}
                                ]

postgresql_users              : [
                                  {name: "user_database", pass: "{{ postgresql_users }}"},
                                  {name: "qa", pass: "{{ postgresql_users_qa }}"}
                                ]

postgresql_user_privileges    : [
                                  {name: "user_database", db: "database_name"},
                                  {name: "qa", db: "database_name_qa"}
                                ]
